Create Load_VIP_DeathInformantPr.sql
massgov/21strvrs pull request #10
Opened 2022-10-14 21:47 UTC by frahmanr

10/14/2022 First version

2022-10-18 19:01 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/Load_VIP_DeathInformantPr.sql
> +
Add one validation that compare code in INFO_RELATION_LIST and INFO_RELATION

2022-10-18 19:01 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/Load_VIP_DeathInformantPr.sql
> +					  ,P.PersonId ,INFO_NME FirstName,INFO_LST_NME LastName,INFO_MIDD_NME MiddleName,ISNULL(INFO_SUFFIX,'NULL') Suffix,INFO_RELATION_LIST RelationList,ISNULL(INFO_RELATION,'NULL') InformantRelation,
Replace iSNULL by COALESCE

2022-10-18 19:06 UTC, almabekwoldesenbet requested changes
Modified Code layout accordingly 

To generate the prod version 
  Set three variables
-    DECLARE     @Workdb VARCHAR(128) = '[RVRS_testdb].',  -- For PROD leave this blank or set to @stagingdb 
-   DECLARE    @targetloc varchar(128) =@Workdb --'[RVRS_PROD].[RVRS_ODS].' For PROD replace this by [RVRS_PROD].[RVRS_ODS]. 
- @testflag bit = 1 -- set this to 0 for production 

**then** 
Load data to ODS  

**Send final code review**

2022-10-20 18:31 UTC, frahmanr commented on RVRS_Staging/Database/Procedure/Load_VIP_DeathInformantPr.sql
> +
Fixed it.

2022-10-20 18:32 UTC, frahmanr commented on RVRS_Staging/Database/Procedure/Load_VIP_DeathInformantPr.sql
> +					  ,P.PersonId ,INFO_NME FirstName,INFO_LST_NME LastName,INFO_MIDD_NME MiddleName,ISNULL(INFO_SUFFIX,'NULL') Suffix,INFO_RELATION_LIST RelationList,ISNULL(INFO_RELATION,'NULL') InformantRelation,
Fixed it.

2022-10-20 20:23 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/Load_VIP_DeathInformantPr.sql
> -					  ,P.PersonId ,INFO_NME FirstName,INFO_LST_NME LastName,INFO_MIDD_NME MiddleName,ISNULL(INFO_SUFFIX,'NULL') Suffix,INFO_RELATION_LIST RelationList,ISNULL(INFO_RELATION,'NULL') InformantRelation,
Remove TOP 10000000
@top VARCHAR(128) =  'TOP 10000000 ' -- For PROD leave this blank

2022-10-20 20:31 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/Load_VIP_DeathInformantPr.sql
> +
Add Bracket (InformantRelation IS NULL AND RelationList  IS NOT NULL) THEN

OR do this 

Add one more variable on code layout : @AdditionalJoin  VARCHAR (MAX) = 

'LEFT JOIN [RVRS_PROD].[RVRS_ODS].[RVRS].[DimInformantRelation] DS on convert (int,d.INFO_RELATION_LIST) = ds.Code and 

And add below replace all the 17 OR entries by 
COALESCE (d.InformantRelation, '')  <> COALESCE (ds.InformantRelationDesc , '')

@AdditionalJoin  should be added at SELECT statement Line between 388 and 389

2022-10-20 20:37 UTC, almabekwoldesenbet requested changes
Data change 
MiddleName 

-  Add   - conversion table 
Informant Other 
- remove Duplicate 
OtherInformantRelationDesc	(No column name)
COUSIN	2
DAUGHTER-IN-LAW	2
EX-WIFE	2
EX-WIFE,HCP	2
GRANDDAUGHTER-IN-LAW	2
MATERNAL GRANDMOTHER	2
PERSONAL REPRESENTATIVE	2
PERSONAL RESPRESENTATIVE	3
SIGNIFICANT OTHER	2
STEP-CHILD	2
STEP-DAUGHTER POA	2
STEP-FATHER/LEGAL GUARDIAN	2
STEP-SON	2

2022-10-21 13:23 UTC, almabekwoldesenbet commented
10-21-2022 - RVRS_169 was completed. First load to ODS about 466699 records were loaded successfully

2022-10-21 13:23 UTC, merged