Code review rvrs.load vip veteran other atr pr
massgov/21strvrs pull request #11
Opened 2022-10-17 19:54 UTC by sailendrasingh1

ITEM 153
Procedure: RVRS.Load_VIP_VeteranOtherAtrPr

2022-10-17 20:39 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_VeteranOtherAtrPr.sql
> +	        ,CASE WHEN VeteranEntries = 1 AND (WAR1 IS NULL OR WAR2 IS NOT NULL OR WAR3 IS NOT NULL) THEN 'VeteranEntries|Warning:Veteran Entry and War Entered Mismatch' ELSE '' END AS LoadNote_3
SSA

2022-10-17 20:40 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_VeteranOtherAtrPr.sql
> +	        ,CASE WHEN VeteranEntries = 2 AND (WAR1 IS NULL OR WAR2 IS NULL OR WAR3 IS NOT NULL) THEN 'VeteranEntries|Warning:Veteran Entry and War Entered Mismatch' ELSE '' END AS LoadNote_4
SSA

2022-10-17 20:40 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_VeteranOtherAtrPr.sql
> +
SSA

2022-10-17 20:54 UTC, almabekwoldesenbet requested changes
Minor changes - you can create Prod Version with the requested fixes

2022-10-18 19:17 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_VeteranOtherAtrPr.sql
> +	        ,CASE WHEN VeteranEntries = 0 AND (WAR1 IS NOT NULL OR WAR2 IS NOT NULL OR WAR3 IS NOT NULL) THEN 'VeteranEntries|Warning:Veteran Entry and War Entered Mismatch' ELSE '' END AS LoadNote_2
added DimWarId in the header section

2022-10-18 19:17 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_VeteranOtherAtrPr.sql
> +	        ,CASE WHEN VeteranEntries = 1 AND (WAR1 IS NULL OR WAR2 IS NOT NULL OR WAR3 IS NOT NULL) THEN 'VeteranEntries|Warning:Veteran Entry and War Entered Mismatch' ELSE '' END AS LoadNote_3
added DimWarId in the header section

2022-10-18 19:17 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_VeteranOtherAtrPr.sql
> +	        ,CASE WHEN VeteranEntries = 2 AND (WAR1 IS NULL OR WAR2 IS NULL OR WAR3 IS NOT NULL) THEN 'VeteranEntries|Warning:Veteran Entry and War Entered Mismatch' ELSE '' END AS LoadNote_4
added DimWarId in the header section

2022-10-18 20:29 UTC, almabekwoldesenbet approved these changes
looks good now

2022-10-18 20:30 UTC, merged