Create RVRS.Load_VIP_DeathMedicalRecordPr.sql
massgov/21strvrs pull request #13
Opened 2022-10-26 19:05 UTC by sailendrasingh1

RVRS.Load_VIP_DeathMedicalRecordPr.sql
First Draft

2022-10-28 19:04 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +					  ,@CurentTime AS CreatedDate
Remove all the IF else part please 
ELSE SUBSTRING(TOD_ME,0,CHARINDEX(':',TOD_ME,1)) END DeathHour,CASE WHEN RIGHT(TOD_ME,2) = 99 THEN '99'
the first query should only be select- NO case statement

2022-10-28 19:14 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +					  ,VRV_REC_DATE_CREATED AS SrCreatedDate
('RIGHT(DOD_4_FD,4)',1,'','','DeathYear', 'VARCHAR(128)', NULL,NULL ),
('LEFT(DOD_4_FD,2)',1,'','','DeathMonth', 'VARCHAR(128)', NULL,NULL ),
('SUBSTRING(DOD_4_FD,4,2)',1,'','','DeathDay', 'VARCHAR(128)', NULL,NULL ),   


This should be DOD_4_FD?

2022-10-28 19:29 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +					  ,VRV_REC_DATE_CREATED AS SrCreatedDate
remove 
('CASE WHEN LEFT(TOD_ME,2) = 99 THEN ''99''
		ELSE SUBSTRING(TOD_ME,0,CHARINDEX('':'',TOD_ME,1)) END',1,'','','DeathHour', 'VARCHAR(128)', NULL,NULL ),
('CASE WHEN RIGHT(TOD_ME,2) = 99 THEN ''99''
		ELSE SUBSTRING(TOD_ME,CHARINDEX('':'',TOD_ME,1)+1,LEN(TOD_ME)) END',1,'','','DeathMinute', 'VARCHAR(128)', NULL,NULL ),

2022-10-28 19:47 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN COALESCE(FirstName,'')<>COALESCE(FirstNameTab1,'') THEN 'FirstName,FirstNameTab1|Warning:FirstName in Tab 1 and Tab 6 Mismatch' ELSE '' END AS LoadNote_1
use the name of target table name when the column is in another table Person.FirstName

2022-10-28 19:50 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN LEFT(FirstName,1) LIKE '[^a-zA-Z]' and FirstName NOT LIKE '-%' THEN 'FirstName|Error:FirstName does not start with Alphabet' ELSE '' END AS LoadNote_2
SSA

2022-10-28 19:50 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN COALESCE(MiddleName,'')<>COALESCE(MiddleNameTab1,'') THEN 'MiddleName,MiddleNameTab1|Warning:MiddleName in Tab 1 and Tab 6 Mismatch' ELSE '' END AS LoadNote_3
Same as Above

2022-10-28 19:51 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN COALESCE(LastName,'')<>COALESCE(LastNameTab1,'') THEN 'LastName,LastNameTab1|Warning:LastName in Tab 1 and Tab 6 Mismatch' ELSE '' END AS LoadNote_5
SSA

2022-10-28 19:54 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (NoMiddleName = 'Y' AND MiddleName IS NOT NULL) OR (NoMiddleName = 'N' AND MiddleName IS NULL) THEN 'MiddleName,NoMiddleName|Warning:MiddleName and NoMiddleName field Mismatch' EL
Use source column name in this case ME_MNAME_NONE

2022-10-28 19:54 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN COALESCE(Suffix,'')<>COALESCE(SuffixTab1,'') THEN 'Suffix,SuffixTab1|Warning:Suffix in Tab 1 and Tab 6 Mismatch' ELSE '' END AS LoadNote_8
SSA

2022-10-28 19:54 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN ISDATE(REPLACE(REPLACE (COALESCE(DOB,'01/01/1900'),'/9999', '/1900'),'99/','01/'))=0 THEN 'DOB|Error:Not a valid Date of Birth' ELSE '' END AS LoadNote_10
Same above

2022-10-28 19:55 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN COALESCE(Sex,'')<>COALESCE(SexTab1,'') THEN 'Sex,SexTab1|Warning:Sex in Tab 1 and Tab 6 Mismatch' ELSE '' END AS LoadNote_9
SSA

2022-10-28 19:56 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN ISDATE(REPLACE(REPLACE (COALESCE(DOB,'01/01/1900'),'/9999', '/1900'),'99/','01/'))=0 THEN 'DOB|Error:Not a valid Date of Birth' ELSE '' END AS LoadNote_10
For this case use DOB_ME for the column name

2022-10-28 20:05 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (TRY_CAST(COALESCE(BirthYear,'1900') AS INT) IS NULL OR TRY_CAST(BirthYear AS INT) <= 1890) AND TRY_CAST(BirthYear AS INT)<>9999 THEN 'BirthYear|Error:Invalid Birth Year' ELSE ''
Let go only COALESCE(TRY_CAST(BirthYear AS INT), '1701') <= 1890) AND TRY_CAST(BirthYear AS INT)<>9999

2022-10-28 20:18 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN TRY_CAST (DOB AS DateTime)>Try_Cast (DOD AS DateTime) THEN 'DOB,DOD|Error:Date of Birth is greater than Date of Death' ELSE '' END AS LoadNote_14
Use source column names

2022-10-28 20:19 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN ISDATE(REPLACE(REPLACE (COALESCE(DOD,'01/01/1900'),'/9999', '/1900'),'99/','01/'))=0 THEN 'DOD|Error:Not a valid Date of Death' ELSE '' END AS LoadNote_15
Use source column name

2022-10-28 20:22 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (TRY_CAST(COALESCE(DeathYear,'1900') AS INT) IS NULL OR TRY_CAST(DeathYear AS INT) <= 1890) AND TRY_CAST(DeathYear AS INT)<>9999 THEN 'DeathYear|Error:Invalid Death Year' ELSE ''
change this 1890 to 2014

2022-10-28 20:22 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN COALESCE(DOD,'')<>COALESCE(DODTab1,'') THEN 'DOD,DODTab1|Warning:Date of Death in Tab1 and Tab6 Mismatch' ELSE '' END AS LoadNote_19
Use the source column name

2022-10-28 20:23 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN ISDATE(DOD) = 1 AND YEAR(CAST(DOD AS DATE))<2014 AND YEAR(CAST(DOD AS DATE))>YEAR(GETDATE()) THEN 'DOD|Warning:Year of Death is before 2014 or later than today' ELSE '' END AS Loa
Remove this. It was covered above

2022-10-28 20:25 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (TRY_CAST(COALESCE(DeathDay,'1') AS INT) IS NULL OR TRY_CAST(REPLACE(DeathDay,'99','1') AS INT) NOT BETWEEN 1 AND 31) THEN 'DeathDay|Error:Invalid Death Day' ELSE '' END AS LoadNo
Removed

2022-10-28 20:25 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (TRY_CAST(COALESCE(DeathMonth,'1') AS INT) IS NULL OR TRY_CAST(REPLACE(DeathMonth,'99','1') AS INT) NOT BETWEEN 1 AND 12) THEN 'DeathMonth|Error:Invalid Death Month' ELSE '' END A
Removed

2022-10-28 20:26 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN ISDATE(REPLACE(REPLACE (COALESCE(DOD,'01/01/1900'),'/9999', '/1900'),'99/','01/'))=0 THEN 'DOD|Error:Not a valid Date of Death' ELSE '' END AS LoadNote_15
DOD must be known. 
ISDATE(REPLACE(DOD)=0

2022-10-28 20:33 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +								 OR (SUBSTRING(TOD,CHARINDEX(':',TOD,1)+1,LEN(TOD)) >60 OR SUBSTRING(TOD,CHARINDEX(':',TOD,1)+1,LEN(TOD))<0) THEN 'TOD|Error:TOD|Error:Death Hour and Minute not in valid range' ELSE '' END AS
You did not follow the code layout logic

2022-10-28 20:35 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +								 OR (SUBSTRING(ProTod,CHARINDEX(':',ProTod,1)+1,LEN(ProTod)) >60 OR SUBSTRING(ProTod,CHARINDEX(':',ProTod,1)+1,LEN(ProTod))<0) THEN 'ProTod|Error:Death Hour and Minute not in valid range' ELS
Follow the code layout

2022-10-28 20:38 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN ISDATE(REPLACE(REPLACE (COALESCE(ProDOD,'01/01/1900'),'/9999', '/1900'),'99/','01/'))=0 THEN 'ProDOD|Error:Not a valid Pronounced Date of Death' ELSE '' END AS LoadNote_23
Use source column

2022-10-28 20:39 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN TOD LIKE '12:00' AND TimeInd NOT IN ('N','D') THEN 'TOD,TimeInd|Warning:Time of Death not in align with Time Indicator' ELSE '' END AS LoadNote_22
Remove this. This will be validated during data conversion

2022-10-28 20:43 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN ProTod LIKE '12:00' AND PronouncedTimeInd NOT IN ('N','D') THEN 'ProTod,PronouncedTimeInd|Warning:Pronounced Time of Death not in align with Pronounced Time Indicator' ELSE '' END
Remove : This should be included in the converson

2022-10-28 20:44 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (TRY_CAST(COALESCE(PronouncedMonth,'1') AS INT) IS NULL OR TRY_CAST(REPLACE(PronouncedMonth,'99','1') AS INT) NOT BETWEEN 1 AND 12) THEN 'PronouncedMonth|Error:Invalid Pronounced
Remove

2022-10-28 20:44 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (TRY_CAST(COALESCE(PronouncedYear,'1900') AS INT) <= 1890) AND TRY_CAST(PronouncedYear AS INT)<>9999 THEN 'PronouncedYear|Error:Invalid Pronounced Year of Death' ELSE '' END AS Lo
REmoved

2022-10-28 20:44 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN COALESCE(ProDOD,'')<>COALESCE(ProDODTab1,'') THEN 'ProDOD,ProDODTab1|Warning:Pronounced Date of Death in Tab1 and Tab6 Mismatch' ELSE '' END AS LoadNote_27
Use source column

2022-10-28 20:45 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (TRY_CAST(COALESCE(PronouncedDay,'1') AS INT) IS NULL OR TRY_CAST(REPLACE(PronouncedDay,'99','1') AS INT) NOT BETWEEN 1 AND 31) THEN 'PronouncedDay|Error:Invalid Pronounced Day of
Remove instead add similar logic as DOD

2022-10-28 20:45 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN TRY_CAST (ProDOD AS DateTime)<Try_Cast (DOD AS DateTime) THEN 'ProDOD,DOD|Error:Pronounced Date of Death is before Date of Death' ELSE '' END AS LoadNote_28
Use source column

2022-11-02 16:11 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +					  ,@CurentTime AS CreatedDate
Fixed

2022-11-02 16:11 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +					  ,VRV_REC_DATE_CREATED AS SrCreatedDate
fixed

2022-11-02 16:12 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN COALESCE(FirstName,'')<>COALESCE(FirstNameTab1,'') THEN 'FirstName,FirstNameTab1|Warning:FirstName in Tab 1 and Tab 6 Mismatch' ELSE '' END AS LoadNote_1
Changed according to discussion.

2022-11-02 16:12 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN LEFT(FirstName,1) LIKE '[^a-zA-Z]' and FirstName NOT LIKE '-%' THEN 'FirstName|Error:FirstName does not start with Alphabet' ELSE '' END AS LoadNote_2
Changed according to discussion.

2022-11-02 16:12 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN COALESCE(MiddleName,'')<>COALESCE(MiddleNameTab1,'') THEN 'MiddleName,MiddleNameTab1|Warning:MiddleName in Tab 1 and Tab 6 Mismatch' ELSE '' END AS LoadNote_3
Changed according to discussion.

2022-11-02 16:13 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (NoMiddleName = 'Y' AND MiddleName IS NOT NULL) OR (NoMiddleName = 'N' AND MiddleName IS NULL) THEN 'MiddleName,NoMiddleName|Warning:MiddleName and NoMiddleName field Mismatch' EL
Changed according to discussion.

2022-11-02 16:14 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN COALESCE(Suffix,'')<>COALESCE(SuffixTab1,'') THEN 'Suffix,SuffixTab1|Warning:Suffix in Tab 1 and Tab 6 Mismatch' ELSE '' END AS LoadNote_8
Fixed

2022-11-02 16:14 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN ISDATE(REPLACE(REPLACE (COALESCE(DOB,'01/01/1900'),'/9999', '/1900'),'99/','01/'))=0 THEN 'DOB|Error:Not a valid Date of Birth' ELSE '' END AS LoadNote_10
Used ME_DOB as per discussion

2022-11-02 16:15 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN TRY_CAST (DOB AS DateTime)>Try_Cast (DOD AS DateTime) THEN 'DOB,DOD|Error:Date of Birth is greater than Date of Death' ELSE '' END AS LoadNote_14
used ME_DOB as per discussion

2022-11-02 16:15 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN ISDATE(REPLACE(REPLACE (COALESCE(DOD,'01/01/1900'),'/9999', '/1900'),'99/','01/'))=0 THEN 'DOD|Error:Not a valid Date of Death' ELSE '' END AS LoadNote_15
Fixed

2022-11-02 16:16 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (TRY_CAST(COALESCE(DeathYear,'1900') AS INT) IS NULL OR TRY_CAST(DeathYear AS INT) <= 1890) AND TRY_CAST(DeathYear AS INT)<>9999 THEN 'DeathYear|Error:Invalid Death Year' ELSE ''
fixed

2022-11-02 16:16 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (TRY_CAST(COALESCE(DeathMonth,'1') AS INT) IS NULL OR TRY_CAST(REPLACE(DeathMonth,'99','1') AS INT) NOT BETWEEN 1 AND 12) THEN 'DeathMonth|Error:Invalid Death Month' ELSE '' END A
removed

2022-11-02 16:16 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN COALESCE(DOD,'')<>COALESCE(DODTab1,'') THEN 'DOD,DODTab1|Warning:Date of Death in Tab1 and Tab6 Mismatch' ELSE '' END AS LoadNote_19
fixed

2022-11-02 16:17 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +								 OR (SUBSTRING(TOD,CHARINDEX(':',TOD,1)+1,LEN(TOD)) >60 OR SUBSTRING(TOD,CHARINDEX(':',TOD,1)+1,LEN(TOD))<0) THEN 'TOD|Error:TOD|Error:Death Hour and Minute not in valid range' ELSE '' END AS
fixed

2022-11-02 16:18 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN TOD LIKE '12:00' AND TimeInd NOT IN ('N','D') THEN 'TOD,TimeInd|Warning:Time of Death not in align with Time Indicator' ELSE '' END AS LoadNote_22
keeping this as per discussion

2022-11-02 16:18 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN ISDATE(REPLACE(REPLACE (COALESCE(ProDOD,'01/01/1900'),'/9999', '/1900'),'99/','01/'))=0 THEN 'ProDOD|Error:Not a valid Pronounced Date of Death' ELSE '' END AS LoadNote_23
fixed

2022-11-02 16:18 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (TRY_CAST(COALESCE(PronouncedMonth,'1') AS INT) IS NULL OR TRY_CAST(REPLACE(PronouncedMonth,'99','1') AS INT) NOT BETWEEN 1 AND 12) THEN 'PronouncedMonth|Error:Invalid Pronounced
fixed

2022-11-02 16:18 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (TRY_CAST(COALESCE(PronouncedYear,'1900') AS INT) <= 1890) AND TRY_CAST(PronouncedYear AS INT)<>9999 THEN 'PronouncedYear|Error:Invalid Pronounced Year of Death' ELSE '' END AS Lo
fixed

2022-11-02 16:18 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN (TRY_CAST(COALESCE(PronouncedDay,'1') AS INT) IS NULL OR TRY_CAST(REPLACE(PronouncedDay,'99','1') AS INT) NOT BETWEEN 1 AND 31) THEN 'PronouncedDay|Error:Invalid Pronounced Day of
logic added

2022-11-02 16:19 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN TRY_CAST (ProDOD AS DateTime)<Try_Cast (DOD AS DateTime) THEN 'ProDOD,DOD|Error:Pronounced Date of Death is before Date of Death' ELSE '' END AS LoadNote_28
fixed

2022-11-02 16:19 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +								 OR (SUBSTRING(ProTod,CHARINDEX(':',ProTod,1)+1,LEN(ProTod)) >60 OR SUBSTRING(ProTod,CHARINDEX(':',ProTod,1)+1,LEN(ProTod))<0) THEN 'ProTod|Error:Death Hour and Minute not in valid range' ELS
fixed

2022-11-02 16:19 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN ProTod LIKE '12:00' AND PronouncedTimeInd NOT IN ('N','D') THEN 'ProTod,PronouncedTimeInd|Warning:Pronounced Time of Death not in align with Pronounced Time Indicator' ELSE '' END
keeping this as per discussion

2022-11-03 15:09 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN ME_TOD LIKE '12:00' AND TimeInd NOT IN ('N','D') THEN 'ME_TOD,ME_TOD_IN|Error:Time of Death not in align with Time Indicator' ELSE '' END AS LoadNote_24
Since TimeInd exists in the target column ME_TOD,ME_TOD_IN| to ME_TOD,TimeInd |

2022-11-03 15:11 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +	        ,CASE WHEN ME_PRO_TIME<>ProTimeTab5A THEN 'ME_PRO_TIME,PRO_TIME|Warning:Pronounced Time of Death in Pronouncement and Certfier Mismatch' ELSE '' END AS LoadNote_30
Add Coaleasce

2022-11-03 15:11 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathMedicalRecordPr.sql
> +							AND ISDATE(ME_PRO_TIME + REPLACE(REPLACE(PronouncedTimeInd,'A','AM'),'P','PM')) = 0)) THEN 'ME_PRO_TIME|Error:Time of Pronouncement is not in a valid range' ELSE '' END AS LoadNote_31
ADD PronouncedTimeInd  column to loadNote

2022-11-03 15:20 UTC, almabekwoldesenbet requested changes
Code layout correction : table name is wrong
('FirstName','Data_Conversion','DeathMedicalRecord_FirstName' ,'FirstName','Fact', 'VARCHAR(128)',1, NULL, NULL),
	('MiddleName','Data_Conversion','DeathMedicalRecord_MiddleName' ,'MiddleName','Fact', 'VARCHAR(128)',1, NULL, NULL),
	('LastName','Data_Conversion','DeathMedicalRecord_LastName' ,'LastName','Fact', 'VARCHAR(128)',1, NULL, NULL),

**Corrected entries** 
	('FirstName','DeathMedicalRecord_FirstName','FirstName' ,'','Fact', 'VARCHAR(128)',1, NULL, NULL),
	('MiddleName','DeathMedicalRecord_MiddleName','MiddleName' ,'','Fact', 'VARCHAR(128)',1, NULL, NULL),
	('LastName','DeathMedicalRecord_LastName','LastName' ,'','Fact', 'VARCHAR(128)',1, NULL, NULL),

**These two are missing** 
ME_CASE_NUM needs conversion for UNKNOWN 
MED_REC_NUM may need conversion for unknown

2022-11-08 14:47 UTC, almabekwoldesenbet approved these changes
looks good

2022-11-08 14:54 UTC, merged