Update RVRS.Load_VIP_DeathPr.sql
massgov/21strvrs pull request #15
Opened 2022-12-08 16:04 UTC by sailendrasingh1

Updated to get extra data

2022-12-12 22:22 UTC, almabekwoldesenbet requested changes
Over all looks good. Dod_4_FD should be mapped here. It's inconsistence with mapping doc.  In addition DOD is already mapped in other table

2022-12-12 22:22 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
> +						THEN 'DimDeathMannerId|Warning:Manner of Death is blank for Registered Record' ELSE '' END AS LoadNote_17
This should be error

2022-12-12 22:22 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
> +					,CASE WHEN TOBAC NOT IN ('Y','N','U',NULL)
This can be removed since it's covered at the bottom. I'll update the mapping document accordingly

2022-12-12 22:22 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
**This section should be modified according to the latest code layout out. Important** 

>

2022-12-30 16:13 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
> +						THEN 'DimPregnancyStatusId,SEX|Error:Pregnancy Status and Sex Mismatch' ELSE '' END AS LoadNote_19
FIXED

2022-12-30 16:20 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
> +						THEN 'DimCertifierDesignId,CERT_DESIG_CODE,CERT_DESIG|Error:Certifier Designation and Certifier Designation Code Mismatch' ELSE '' END AS LoadNote_22
Fixed

2022-12-30 16:20 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
> +						THEN 'DimDeathMannerId|Warning:Manner of Death is blank for Registered Record' ELSE '' END AS LoadNote_17
Fixed

2022-12-30 16:22 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
> +					,CASE WHEN TOBAC NOT IN ('Y','N','U',NULL)
Removed

2022-12-30 20:39 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
> -					,CASE WHEN ISDATE(D.DOD_4_FD) = 1 THEN MONTH(CAST(D.DOD_4_FD AS DATE))
Fixed

2022-12-30 20:39 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
> +						  WHEN D.DOD LIKE '[0-9][0-9]/99/9999'THEN LEFT(D.DOD,2)
Fixed

2022-12-30 20:39 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
> +						  WHEN D.DOD LIKE '99/[0-9][0-9]/9999'THEN SUBSTRING(D.DOD,4,2)
Fixed

2022-12-30 20:39 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
> +						  WHEN ISDATE(D.DOD) = 0 AND D.DOD <> '99/99/9999' THEN 'DOD|Error:NOT A VALID DATE'
kept as per discussion

2022-12-30 20:39 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
> +							THEN 'RecordType,DSTATEL|Error:RecordType & Death State  Mismatch'
Fixed

2022-12-30 20:40 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
>  						THEN 'TOD|Warning:Death Hour and Minute Mismatch in Tab 1 and Tab 6' ELSE '' END AS LoadNote_12
Fixed

2022-12-30 20:40 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
> +						THEN 'SfnType|Warning:SfnType & RecordType Mismatch' ELSE '' END AS LoadNote_15
Fixed

2022-12-30 20:41 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathPr.sql
Fixed

2023-01-05 19:09 UTC, almabekwoldesenbet approved these changes
looks good

2023-01-05 19:10 UTC, almabekwoldesenbet commented
looks good

2023-01-05 19:11 UTC, merged