Create RVRS.Load_VIP_DeathRegistrationPr.sql
massgov/21strvrs pull request #18
Opened 2023-01-23 14:53 UTC by sailendrasingh1

1/23/2023

2023-01-24 14:10 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +	CREATE TABLE [RVRS_testdb].[RVRS].[DeathRegistration_Log] (Id BIGINT IDENTITY (1,1), SrId VARCHAR(64), RegistrationNumber_DC VARCHAR(128),DepositionNumber_DC VARCHAR(128),RegVolume_DC VARCHAR(128),R
Code layout version is different 
[FlRegistered] VARCHAR(16),[FlArchived] VARCHAR(16),[FlAcknowledge] VARCHAR(16) - procedure 
[FlRegistered] VARCHAR(8),[SrcRegistererUserId] INT,[FlSearchable] VARCHAR(8) - code layout

2023-01-24 14:19 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +
I think, it would be nice to filter data by RESIDE_REGIS_DATE. Filter can be added to this field using filtercondition = IS NOT NULL , filterconditionOpr =''

2023-01-24 14:57 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +					  ,@CurentTime AS CreatedDate
('NULL',1,'','','PageEntryTypeId', 'VARCHAR(128)', 1,'''NULL'''),
('NULL',1,'','','RecordAccessId', 'VARCHAR(128)', 1,'''NULL'''),
it would be nice to alias it to PageEntryType and RecordAccess because they are not Ids

2023-01-24 16:32 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +	        ,CASE WHEN Try_Cast(OCCUR_REGIS_DATE AS DateTime)>Try_Cast(RESIDE_REGIS_DATE AS DateTime)
This is only true when version is 0. Add VRV_REC_REPLACE_NBR = 0

2023-01-24 16:41 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +						OR Try_Cast(OCCUR_REGIS_DATE AS DateTime)>Try_Cast(ST_REGIS_DATE AS DateTime) THEN 'OCCUR_REGIS_DATE,RESIDE_REGIS_DATE,ST_REGIS_DATE|Error:Date of Occurance must be first' ELSE '' END AS LoadNo
remove CASE WHEN Try_Cast(OCCUR_REGIS_DATE AS DateTime)>Try_Cast(RESIDE_REGIS_DATE AS DateTime) 
						OR Try_Cast(OCCUR_REGIS_DATE AS DateTime)>Try_Cast(ST_REGIS_DATE AS DateTime) THEN 'OCCUR_REGIS_DATE,RESIDE_REGIS_DATE,ST_REGIS_DATE|Error:Date of Occurance must be first' ELSE '' END AS LoadNote_9 since it was converted on LoadNote_4

2023-01-24 18:30 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +		INTO #Tmp_HoldData_Final
you should add case for 
FlRegistered Value should be N, Y or NULL, otherwise log error and keep it ASIDE.
FlSearchable Value should be N, Y or NULL, otherwise log error and keep it ASIDE.

2023-01-24 18:37 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +	CREATE TABLE [RVRS_testdb].[RVRS].[DeathRegistration_Log] (Id BIGINT IDENTITY (1,1), SrId VARCHAR(64), RegistrationNumber_DC VARCHAR(128),DepositionNumber_DC VARCHAR(128),RegVolume_DC VARCHAR(128),R
remove the last id from the alias- PageEntryTypeId and RecordAccessId 
PageEntryType, RecordAccess

2023-01-24 18:38 UTC, almabekwoldesenbet requested changes
Over all it looks good except few things

2023-01-26 18:36 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +	CREATE TABLE [RVRS_testdb].[RVRS].[DeathRegistration_Log] (Id BIGINT IDENTITY (1,1), SrId VARCHAR(64), RegistrationNumber_DC VARCHAR(128),DepositionNumber_DC VARCHAR(128),RegVolume_DC VARCHAR(128),R
Nothing to fix

2023-01-26 18:39 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +
we will visit again if table is big

2023-01-26 18:39 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +					  ,@CurentTime AS CreatedDate
fixed

2023-01-26 18:44 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +	        ,CASE WHEN Try_Cast(OCCUR_REGIS_DATE AS DateTime)>Try_Cast(RESIDE_REGIS_DATE AS DateTime)
Fixed

2023-01-26 18:44 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +						OR Try_Cast(OCCUR_REGIS_DATE AS DateTime)>Try_Cast(ST_REGIS_DATE AS DateTime) THEN 'OCCUR_REGIS_DATE,RESIDE_REGIS_DATE,ST_REGIS_DATE|Error:Date of Occurance must be first' ELSE '' END AS LoadNo
Removed

2023-01-26 18:45 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +	        ,CASE WHEN FlArchived NOT IN ('N','Y',NULL) THEN 'FlArchived|Error:Not a valid value for FlArchived' ELSE '' END AS LoadNote_13
Fixed

2023-01-26 18:47 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +		INTO #Tmp_HoldData_Final
added

2023-01-26 18:47 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationPr.sql
> +	CREATE TABLE [RVRS_testdb].[RVRS].[DeathRegistration_Log] (Id BIGINT IDENTITY (1,1), SrId VARCHAR(64), RegistrationNumber_DC VARCHAR(128),DepositionNumber_DC VARCHAR(128),RegVolume_DC VARCHAR(128),R
fixed

2023-01-30 15:15 UTC, merged