Create RVRS.Load_VIP_DeathRegistrationGeneralPr.sql
massgov/21strvrs pull request #19
Opened 2023-01-24 21:26 UTC by sailendrasingh1

01/24/2023

2023-01-25 22:47 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationGeneralPr.sql
> +					  ,P.PersonId ,RECORD_REGIS_DATE RegistrationDate,COALESCE(RECORD_REGISTRAR,'NULL') RegistrarName,RECORD_REGIS_NUM RegistrationNumber,DATE_OF_AMENDMENT AmendmentDate,COALESCE(IND_ACCESS_STATUS,'
change this from  
('IND_ACCESS_STATUS',1,'','','RecordAccess**Id**', 'VARCHAR(128)',NULL,'''NULL'''),
to 
('IND_ACCESS_STATUS',1,'','','RecordAccess', 'VARCHAR(128)',NULL,'''NULL'''),

('IND_REGIS_STATUS',1,'','','RegistrationStatus**Id**', 'VARCHAR(128)',NULL,'''NULL'''),
to 
('IND_REGIS_STATUS',1,'','','RegistrationStatus', 'VARCHAR(128)',NULL,'''NULL'''),

2023-01-25 22:49 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationGeneralPr.sql
> +		INTO #Tmp_HoldData_Final
removed: 
**FlAmended = 0  AND VRV_REC_REPLACE_NBR <> 0** from LoadNote_22

2023-01-25 22:50 UTC, almabekwoldesenbet requested changes
As the log is big can you confirm it with Avinash

2023-01-26 18:51 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationGeneralPr.sql
> +					  ,P.PersonId ,RECORD_REGIS_DATE RegistrationDate,COALESCE(RECORD_REGISTRAR,'NULL') RegistrarName,RECORD_REGIS_NUM RegistrationNumber,DATE_OF_AMENDMENT AmendmentDate,COALESCE(IND_ACCESS_STATUS,'
fixed

2023-01-26 18:52 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathRegistrationGeneralPr.sql
> +		INTO #Tmp_HoldData_Final
removed

2023-01-30 16:32 UTC, almabekwoldesenbet approved these changes

2023-01-30 16:41 UTC, merged