Create RVRS.Load_VIP_DeathFuneralHomePr.sql
massgov/21strvrs pull request #28
Opened 2023-06-07 19:15 UTC by sailendrasingh1

Funeral Home Code for Review 06/07/2023

2023-06-08 15:39 UTC, almabekwoldesenbet requested changes
it looks great just a couple of corrections.

2023-06-08 15:39 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathFuneralHomePr.sql
> +	        ,CASE WHEN (FNRL_SERVICE_OOS = 'N' and FH_RESPONSIBLE_NAME<> FNRL_NME) THEN 'FNRL_SERVICE_OOS,RESPONSIBE_NAME,FNRL_NME|Error:Funeral Home and Responsible Funeral Home names are different for
Modify the error msg .
Funeral Home and Responsible Funeral Home names are different for **_none_** Trade Service Call

2023-06-14 18:28 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathFuneralHomePr.sql
> +	        ,CASE WHEN (FNRL_SERVICE_OOS = 'Y' and FH_RESPONSIBLE_NAME= FNRL_NME) THEN 'FNRL_SERVICE_OOS,RESPONSIBE_NAME,FNRL_NME|Error:Funeral Home and Responsible Funeral Home names are same for Trade
Fixed

2023-06-14 18:30 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathFuneralHomePr.sql
> +
Fixed

2023-06-15 21:58 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathFuneralHomePr.sql
> +	        ,CASE WHEN DimFuneralHomeTypeInternalId =1 AND FNRL_NME IS NULL THEN 'DimFuneralHomeTypeInternalId,FNRL_NME|Error:Missing Funeral Home Name' ELSE '' END AS LoadNote_4
We have to redone this.  It should be : 
   ,CASE WHEN AND ((FNRL_SERVICE_OOS = 'Y'  AND TRADE_FH_UNLISTED =  'N' ) OR (FNRL_SERVICE_OOS = 'N' FL_FUNERAL_HOME_UNLISTED = 'N')) AND FNRL_NME<>FH_NAME

2023-06-22 19:27 UTC, almabekwoldesenbet approved these changes

2023-06-22 19:27 UTC, merged