Update FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
massgov/21strvrs pull request #33
Opened 2023-06-21 14:14 UTC by rnagaraj22

Updating Amendment for Support description is blank and 2020 records excluded - 6-21-23

2023-06-22 18:49 UTC, almabekwoldesenbet requested changes

2023-06-22 18:49 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  					WHEN C.Field = 'TASK_PLACE_OF_DEATH_ADDRESS_STREET_NUMBER' AND AD.CHANGED_VALUE LIKE '%,%' THEN '99'
same as above

2023-06-22 18:49 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  					WHEN C.Field = 'TASK_DECEDENT_ADDRESS_STREET_NUMBER' AND AD.CHANGED_VALUE LIKE '%,%' THEN '99'
same as above

2023-06-23 20:56 UTC, rnagaraj22 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +					WHEN C.Field = 'TASK_INFORMANT_ADDRESS_STREET_NUMBER' AND ISNUMERIC(AD.ORIGINAL_VALUE)= 0 THEN ISNULL(AD.ORIGINAL_VALUE,'')
Fixed

2023-06-23 20:56 UTC, rnagaraj22 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  					WHEN C.Field = 'TASK_DECEDENT_ADDRESS_STREET_NUMBER' AND ISNUMERIC(AD.ORIGINAL_VALUE)=1 THEN ISNULL(CAST(CAST(REVERSE(REPLACE(AD.ORIGINAL_VALUE,'.','')) AS BIGINT) AS VARCHAR (20)),'')
fixed

2023-06-23 21:30 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  		WHEN DOC.SUPPORT4_DATE IS NULL THEN ''
Modified this instead - DOC.SUPPORT4_DATE IS NULL OR DOC.SUPPORT4_TYPE_CODE

2023-06-23 21:30 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  		END + --80
Since DOC.SUPPORT4_TYPE_CODE was included above remove it from here

2023-06-23 21:31 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  		WHEN ISDATE(DOC.SUPPORT5_DATE)= 0 AND (REPLACE(DOC.SUPPORT5_DATE,'9','') IN ('/', '')) THEN '999999996666'
Do the same thing here

2023-06-23 21:32 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  		WHEN DOC.SUPPORT1_DATE IS NULL THEN ''
Modified this instead - DOC.SUPPORT4_DATE IS NULL OR DOC.SUPPORT4_TYPE_CODE

2023-06-23 21:32 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  	  END + --59
Remove DOC.SUPPORT1_TYPE_CODE from here

2023-06-23 21:33 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  		WHEN ISDATE(DOC.SUPPORT2_DATE)= 0 AND ( REPLACE(DOC.SUPPORT2_DATE,'9','') IN ('/', '')) THEN '999999996666'
Do the same thing here

2023-06-23 21:33 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  	 END + --66
Do the same thing here

2023-06-23 21:33 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  		WHEN DOC.SUPPORT3_DATE IS NULL  THEN ''
Do the same thing here

2023-06-23 21:33 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +		WHEN ISDATE( DOC.SUPPORT3_DATE) = 1 AND (DOC.SUPPORT3_TYPE_CODE IS NOT NULL)THEN ISNULL(CONVERT(VARCHAR ,DATEADD(DAY,+2,CONVERT(DATETIME,DOC.SUPPORT3_DATE )),112) + '6666','999999996666') ELSE ''
Do the same thing here

2023-06-23 21:34 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  		WHEN DOC.SUPPORT4_DATE IS NULL THEN ''
Do the same thing here

2023-06-23 21:34 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  		WHEN DOC.SUPPORT5_DATE IS NULL THEN ''
Do the same thing here

2023-06-23 21:34 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +		WHEN ISDATE( DOC.SUPPORT5_DATE) = 1 AND (DOC.SUPPORT5_TYPE_CODE IS NOT NULL)THEN ISNULL(CONVERT(VARCHAR ,DATEADD(DAY,+2,CONVERT(DATETIME,DOC.SUPPORT5_DATE )),112) + '6666','999999996666') ELSE ''
Do the same thing here

2023-06-26 19:42 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  	  END + --59
fixed

2023-06-26 19:43 UTC, almabekwoldesenbet approved these changes
Looks good

2023-06-26 19:45 UTC, almabekwoldesenbet approved these changes

2023-06-26 20:03 UTC, merged