Update FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
massgov/21strvrs pull request #38
Opened 2023-08-29 17:57 UTC by sailendrasingh1

Amendment 23.1 SP 1
Date: 08/29/2023

2023-08-29 18:59 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  '|' + 'BASIS:' + ISNULL(A.MOD_BASIS,'') + ',' + 'REGISTRATON NUMBER:'+ISNULL(D.RECORD_REGIS_NUM,'') + ',' + 'REASON:'+ ISNULL(D.AMENDMENT_REASON ,'BLANK')+ ',' + 'USER ID:'+ ISNULL(U.USERNAME,'') + '
'REASON:'+ ISNULL(D.AMENDMENT_REASON ,'BLANK') why?
I think it should be  'REASON:'+ ISNULL(D.AMENDMENT_REASON ,'BLANK')

2023-08-29 19:46 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +					WHEN c.Field = 'TASK_DECEDENT_MILITARY_SERVICE_1_MILITARY_START_DATE_LONG' AND ISDATE(AD.ORIGINAL_VALUE)= 0 AND REPLACE(AD.ORIGINAL_VALUE,'9','') IN ('/', '') THEN '99999999' + '6666'   -- dont
WHEN c.Field = 'TASK_DECEDENT_MILITARY_SERVICE_1_MILITARY_START_DATE_LONG' AND ISDATE(AD.ORIGINAL_VALUE)= 0 AND REPLACE(AD.ORIGINAL_VALUE,'9','') IN ('/', '') THEN '99999999' + '6666'
mac do we have this logic in generic load code?

2023-08-29 19:47 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +					WHEN c.Field = 'TASK_DECEDENT_MILITARY_SERVICE_2_MILITARY_START_DATE_LONG' AND ISDATE(AD.ORIGINAL_VALUE)= 0 AND REPLACE(AD.ORIGINAL_VALUE,'9','') IN ('/', '') THEN '99999999' + '6666'   -- dont
Same as above

2023-08-29 19:47 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +					WHEN c.Field = 'TASK_DECEDENT_MILITARY_SERVICE_3_MILITARY_START_DATE_LONG' AND ISDATE(AD.ORIGINAL_VALUE)= 0 AND REPLACE(AD.ORIGINAL_VALUE,'9','') IN ('/', '') THEN '99999999' + '6666'   -- dont
SSA

2023-08-29 19:49 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +					WHEN c.Field = 'TASK_DECEDENT_MILITARY_SERVICE_1_MILITARY_DISCHARGE_DATE_LONG' AND AD.ORIGINAL_VALUE LIKE 'N%A' THEN '666666666666'
WHEN c.Field = 'TASK_DECEDENT_MILITARY_SERVICE_1_MILITARY_DISCHARGE_DATE_LONG' AND AD.ORIGINAL_VALUE LIKE 'N%A' THEN '666666666666'
Does this exist in Generic load code?

2023-08-29 19:57 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +								 WHEN ISDATE(dt.DOI)= 0 AND REPLACE(dt.DOI,'9','') IN ('/', '') THEN '99999999' + CONVERT( VARCHAR,REPLACE(ISNULL(dt.TOI,'6666'),':',''))
WHEN ISDATE(dt.DOI)= 0 AND REPLACE(dt.DOI,'9','') IN ('/', '') THEN '99999999' + CONVERT( VARCHAR,REPLACE(ISNULL(dt.TOI,'6666'),':',''))
Is this logic exist in the generic load code?

2023-08-29 19:59 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +							THEN ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(dt.INFO_ADDR1,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
Why do you scramble ADD1?

2023-08-29 20:07 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +			+ ' ' + CASE WHEN ISNULL(DOC.SUPPORT1_DESCRIPTION,'') <> '' AND ISDATE(DOC.SUPPORT1_DATE)= 0 AND DOC.SUPPORT1_DATE IS NOT NULL THEN ': Support Document Date (VIP) -' + DOC.SUPPORT1_DATE
put comment here.

2023-08-29 20:14 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +ORDER BY 1,RECORD_SORTING
remove this one. it was already added above
select * from [DAVE_MIGRATION].[TRAN_AMEND_GENERATEDTEXT]
--WHERE SFN_NUM = '030965'
ORDER BY 1,RECORD_SORTING

2023-08-29 20:28 UTC, almabekwoldesenbet requested changes
Logically this request does not require. But it's nice to organize. The following fields should be moved in the first part. They have the same scramble logic
TASK_DECEDENT_ADDRESS_STREET_NAME,TASK_PLACE_OF_DEATH_ADDRESS_STREET_NAME

REMOVE TASK_DECEDENT_ADDRESS_STREET_NUMBER' FROM THE ABOVE SECTION IT WILL BE HANDLED IN THE ELSE 

Nice to do: to cleanup code
can you track the list of SFN_Num in another file.  The code looks like huge.


Logically I donot see any issue but make sure the logic is the same as the generic load code

2023-08-30 13:41 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
>  '|' + 'BASIS:' + ISNULL(A.MOD_BASIS,'') + ',' + 'REGISTRATON NUMBER:'+ISNULL(D.RECORD_REGIS_NUM,'') + ',' + 'REASON:'+ ISNULL(D.AMENDMENT_REASON ,'BLANK')+ ',' + 'USER ID:'+ ISNULL(U.USERNAME,'') + '
Fixed

2023-08-30 13:44 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +					WHEN c.Field = 'TASK_DECEDENT_MILITARY_SERVICE_1_MILITARY_START_DATE_LONG' AND ISDATE(AD.ORIGINAL_VALUE)= 0 AND REPLACE(AD.ORIGINAL_VALUE,'9','') IN ('/', '') THEN '99999999' + '6666'   -- dont
Yes. The logic is written like 
WHEN ISDATE(VET1_DATE_ENTERED)= 0 AND REPLACE(VET1_DATE_ENTERED,'9','') IN ('/', '') THEN '99999999' + '6666'

2023-08-30 13:45 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +					WHEN c.Field = 'TASK_DECEDENT_MILITARY_SERVICE_2_MILITARY_START_DATE_LONG' AND ISDATE(AD.ORIGINAL_VALUE)= 0 AND REPLACE(AD.ORIGINAL_VALUE,'9','') IN ('/', '') THEN '99999999' + '6666'   -- dont
Yes. The logic is written like
 WHEN ISDATE(VET2_DATE_ENTERED)= 0 AND REPLACE(VET2_DATE_ENTERED,'9','') IN ('/', '') THEN '99999999' + '6666'

2023-08-30 13:45 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +					WHEN c.Field = 'TASK_DECEDENT_MILITARY_SERVICE_3_MILITARY_START_DATE_LONG' AND ISDATE(AD.ORIGINAL_VALUE)= 0 AND REPLACE(AD.ORIGINAL_VALUE,'9','') IN ('/', '') THEN '99999999' + '6666'   -- dont
Yes. The logic is written like
WHEN ISDATE(VET3_DATE_ENTERED)= 0 AND REPLACE(VET3_DATE_ENTERED,'9','') IN ('/', '') THEN '99999999' + '6666'

2023-08-30 13:46 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +					WHEN c.Field = 'TASK_DECEDENT_MILITARY_SERVICE_1_MILITARY_DISCHARGE_DATE_LONG' AND AD.ORIGINAL_VALUE LIKE 'N%A' THEN '666666666666'
Yes. The logic is written like
 WHEN VET1_DATE_DISCHARGED LIKE 'N%A' THEN '666666666666'

2023-08-30 13:48 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +								 WHEN ISDATE(dt.DOI)= 0 AND REPLACE(dt.DOI,'9','') IN ('/', '') THEN '99999999' + CONVERT( VARCHAR,REPLACE(ISNULL(dt.TOI,'6666'),':',''))
Yes, the logic is written like 
WHEN ISDATE(DOI)= 0 AND REPLACE(DOI,'9','') IN ('/', '') THEN '99999999' + CONVERT( VARCHAR,REPLACE(ISNULL(TOI,'6666'),':',''))

2023-08-30 13:48 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +							THEN ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(dt.INFO_ADDR1,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
previously scrambled, but can be removed

2023-08-30 13:50 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +							THEN ISNULL(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(dt.INFO_ADDR1,'A','C'),'E','X'),'I','Q'),'O','Z'),'U','T'),'B','Q'),'')
Informant address is scrambled in generic script as well hence this has to be scrambled too.

2023-08-30 15:28 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_AMENDMENT_DATA_SCRAMBLING.sql
> +			+ ' ' + CASE WHEN ISNULL(DOC.SUPPORT1_DESCRIPTION,'') <> '' AND ISDATE(DOC.SUPPORT1_DATE)= 0 AND DOC.SUPPORT1_DATE IS NOT NULL THEN ': Support Document Date (VIP) -' + DOC.SUPPORT1_DATE
Fixed

2023-08-30 18:13 UTC, merged