Update FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
massgov/21strvrs pull request #39
Opened 2023-10-06 14:25 UTC by sailendrasingh1

Detail: Code Update for September Release for Scrambled Data 
Date:10-06-2023

2023-10-06 19:26 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> ++ '|' + ISNULL(SFN_NUM_OOS,'')			--258
should be blank

2023-10-06 19:32 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
>  					THEN ISNULL((CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME , BURIAL_PERMIT_ISSUE_DATE )),112 ) + '6666'),'')
CASE WHEN C.CURRENT_CITY_OPT_IN = 'Y' AND BURIAL_PERMIT_ISSUE_DATE IS NULL AND **ISDATE(BURIAL_PERMIT_ISSUE_DATE_RV) = 0** (Why)?
					THEN REPLACE ((RIGHT(BURIAL_PERMIT_ISSUE_DATE,4) + LEFT(BURIAL_PERMIT_ISSUE_DATE,6)),'/','') + '6666' - Is this correct?

2023-10-06 19:41 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> ++ '|' + OCCUR_REGIS_NUM		--261				--REVISITED IN SEPT RELEASE
ISNULL is missing for OCCUR_REGIS_NUM

2023-10-06 20:14 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
>  	   WHEN ISDATE(DOI)= 0 THEN  REPLACE ((RIGHT(DOI,4) + LEFT(DOI,6)),'/','') + REPLACE(ISNULL(TOI,'6666'),':','')
WHEN ISDATE(DOI)= 0 THEN  REPLACE ((RIGHT(DOI,4) + LEFT(DOI,6)),'/','') + REPLACE(ISNULL(TOI,'6666'),':','') 
The same conversion should be applied for the section TOI

which is similar to 
  WHEN ISDATE(DOI) = 1 THEN ISNULL(CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME, DOI)),112),'') 
							+ (CASE WHEN TOI_IND = 'D' AND TOI = '12:00' THEN '0000'
								ELSE CAST(
											(CASE WHEN TOI_IND = 'P'  AND TOI NOT LIKE '12:%' THEN CAST(CAST(LEFT(REPLACE(TOI,':',''),2) AS INT)+12 AS VARCHAR(100)) +CAST(RIGHT(REPLACE(TOI,':',''),2) AS VARCHAR(100))
											   ELSE REPLACE(ISNULL(TOI,'6666'),':','') 
											 END) AS VARCHAR(10))
								END)

2023-10-06 20:23 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> ++ '|' + 'REGISTERED'					--419				--bezawit will check
Did you remember did i checked this as per your comment **"Bezawit will check this"**. I don't see this the mapping

2023-10-06 20:36 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +			 WHEN TOI = '99:99' THEN ''
Is TOI converted to Military? Should not this be converted to Military? We need to check this?

2023-10-06 20:46 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +					   WHEN TOD_IN_ME = 'D' AND TOD_ME = '12:00' THEN '0000'
I think this is wrong. 1200 is noon, 0000 is midnight
  WHEN TOD_IN_ME = 'D' AND TOD_ME = '12:00' THEN '0000' = 1200 is noon
there should be another one 
TOD_IN_ME = 'M' AND TOD_ME = '12:00'   = 0000 is midnight

2023-10-06 20:46 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
>  			WHEN TOD_IN = 'D' AND TOD = '12:00' THEN '0000'
Same as above

2023-10-06 20:50 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +								ELSE CAST(
Same as above

2023-10-06 21:04 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> ++ '|' +  ISNULL(CONVERT(VARCHAR(30),DATEADD(DAY,+2,CONVERT (DATETIME, OCCUR_REGIS_DATE)),112),'') + '6666' --742
Are all the dates date?

2023-10-06 21:08 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> ++ '|' + ISNULL(PH.Mapping_Current_PhysicanTitle,'')			--780
is the  title from att-c?

2023-10-06 21:11 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +			 WHEN VET1_DATE_DISCHARGED LIKE 'N%A' THEN '666666666666'
Why '666666666666' it should be 999999996666

2023-10-06 21:13 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +			 WHEN VET2_DATE_DISCHARGED LIKE 'N%A' THEN '666666666666'
same as above

2023-10-06 21:14 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +			 WHEN VET3_DATE_DISCHARGED LIKE 'N%A' THEN '666666666666'
Same as above

2023-10-06 21:18 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +		END				--857
FL_COD_PENDING  can be NULL

2023-10-06 21:30 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +				THEN ISNULL(CTC2.CLERK_FIRST_NAME,'')+ ';' + ISNULL(CTC2.CLERK_MIDDLE_NAME,'') +';' +ISNULL(CTC2.CLERK_LAST_NAME,'')+ ';' +ISNULL(CTC2.CLERK_SUFFIX,'')
D.RESIDE_REGIS_NAMEL IS NULL AND D.RESIDE_REGIS_NAME IS NOT NULL

2023-10-06 21:31 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +AND DEATH_REC_ID IN (227382,502407)
Remove this

2023-10-06 21:33 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +			 WHEN D.RESIDE_REGIS_NAMEL IS NULL
this should be  WHEN D.RESIDE_REGIS_NAMEL IS NOT NULL AND  D.RESIDE_REGIS_NAMEL IS NULL

2023-10-06 21:34 UTC, almabekwoldesenbet requested changes
I checked almost all. The most important one is TOD and TOI that must be checked

2023-10-10 14:28 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
>  	   WHEN ISDATE(DOI)= 0 THEN  REPLACE ((RIGHT(DOI,4) + LEFT(DOI,6)),'/','') + REPLACE(ISNULL(TOI,'6666'),':','')
D is midnight and N is noon according to the code table. So no changes in code

2023-10-10 14:34 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> ++ '|' + 'REGISTERED'					--419				--bezawit will check
Discussed and Fixed

2023-10-10 14:38 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +					   WHEN TOD_IN_ME = 'D' AND TOD_ME = '12:00' THEN '0000'
Discussed and change is not required

2023-10-10 14:38 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +								ELSE CAST(
Discussed and change is not required

2023-10-10 14:40 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> ++ '|' + ISNULL(PH.Mapping_Current_PhysicanTitle,'')			--780
Created a separated conversion table for this logic

2023-10-10 15:09 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +			 WHEN VET1_DATE_DISCHARGED LIKE 'N%A' THEN '666666666666'
Verified using UI

2023-10-10 15:10 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +AND DEATH_REC_ID IN (227382,502407)
will be removed in Final Version

2023-10-10 15:13 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/FOR_MASTER_GENERIC_DATA_SCRAMBLING.sql
> +			 WHEN D.RESIDE_REGIS_NAMEL IS NULL
FIXED

2023-10-16 19:58 UTC, almabekwoldesenbet approved these changes
looks good

2023-10-16 19:58 UTC, merged