Item no:162 Create RVRS.Load_VIP_DeathCausePr 10/07/2022
massgov/21strvrs pull request #8
Opened 2022-10-07 21:49 UTC by sailendrasingh1

First draft for code review 10/07/2022
Item no:162

2022-10-11 20:54 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,1 AS CauseOrder
This should be A, B, C, D

2022-10-11 20:54 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,2 AS CauseOrder
SSA

2022-10-11 20:54 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,3 AS CauseOrder
SSA

2022-10-11 20:54 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,4 AS CauseOrder
SSA

2022-10-11 20:57 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,CASE WHEN ISNULL(DC.Unit1,'NULL') = '' THEN 'NULL' ELSE DC.UNIT1 END AS Unit1Conv	--Writing a case statement here because replace function is not giving desirable output
What is this for?

2022-10-11 20:57 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,CASE WHEN ISNULL(DC.Unit2,'NULL') = '' THEN 'NULL' ELSE DC.UNIT2 END AS Unit2Conv
SSA

2022-10-11 21:11 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,CASE WHEN CertDesig = 'MEDICAL EXAMINER'  AND CAUSE = 'PENDING' AND CAUSEORDER !=1 AND OtherCause IS NOT NULL
Pending -- CAUSEORDER !='A'
remove AND OtherCause IS NOT NULL 

if pending, it should be A

2022-10-11 21:11 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +					THEN '|| Cause,IntervalOrginal,UnitOriginal|Error:DeathCause is null but Death Interval or Death Unit have value' ELSE '' END AS LoadNote_2
Error message : Cause of death is blank but the interval or unit have value

2022-10-11 21:12 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		INTO #Tmp_HoldData_Filter
One validation is missing. Checking the first Char

2022-10-11 21:17 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		LEFT JOIN [RVRS_PROD].[RVRS_ODS].[RVRS].[DimDeathCauseUnit] DS WITH(NOLOCK) ON DS.Abbr=MT.UnitOriginal
INNER JOIN

2022-10-11 21:17 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		LEFT JOIN [RVRS_PROD].[RVRS_ODS].[RVRS].[DimDeathCauseUnit] DS WITH(NOLOCK) ON DS.Abbr=MT.Unit1Conv
INNER JOIN

2022-10-11 21:17 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		LEFT JOIN [RVRS_PROD].[RVRS_ODS].[RVRS].[DimDeathCauseUnit] DS WITH(NOLOCK) ON DS.Abbr=MT.Unit2Conv
INNER JOIN

2022-10-11 21:22 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +
MT.DimUnitOrginalId --- Cannot be NULL
DimUnit2ConvId  -- Cannot be NULL
DimUnit1ConvId --Cannot be null

These three should be checked - This will be validation error

2022-10-12 13:29 UTC, almabekwoldesenbet requested changes
- send code layout 
- remove filter 
   AND (ISDATE(D.VET1_DATE_ENTERED) =1 AND ISDATE(D.VET1_DATE_DISCHARGED) = 1 
							AND ISDATE(D.VET2_DATE_ENTERED) =1 AND ISDATE(D.VET2_DATE_DISCHARGED) = 1
							AND ISDATE(D.VET3_DATE_ENTERED) =1 AND ISDATE(D.VET3_DATE_DISCHARGED) = 1
							)

validation 
=======
- CASE WHEN DATEDIFF(HOUR,try_Cast (DOB AS DateTime),Try_Cast (DateDischarged AS DateTime))/8766<=15 THEN 'DateDischarged,DOB|Warning:Not a valid DateDischarged with respect to Date of Birth' ELSE '' END AS LoadNote_5 -- this is not wrong
- DateEntered  Verify malformed date, log error   - this is missing 
- DateDischarged - Verify malformed date, log error   - this is missing 

Data conversion 
========
- OtherWar - Std UNK to three dash (---)   - missing

2022-10-13 02:06 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,1 AS CauseOrder
Done!!

2022-10-13 02:06 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,2 AS CauseOrder
Done!!

2022-10-13 02:07 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,3 AS CauseOrder
Done!!

2022-10-13 02:07 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,4 AS CauseOrder
Done!!

2022-10-13 02:08 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,CASE WHEN ISNULL(DC.Unit1,'NULL') = '' THEN 'NULL' ELSE DC.UNIT1 END AS Unit1Conv	--Writing a case statement here because replace function is not giving desirable output
Removed case statement, made changes to data conversion table and replaced '' with DB NULL and brought back ISNULL condition in this line. Fixed!!

2022-10-13 02:08 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,CASE WHEN ISNULL(DC.Unit2,'NULL') = '' THEN 'NULL' ELSE DC.UNIT2 END AS Unit2Conv
Fixed!!

2022-10-13 02:10 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,CASE WHEN CertDesig = 'MEDICAL EXAMINER'  AND CAUSE = 'PENDING' AND CAUSEORDER !=1 AND OtherCause IS NOT NULL
Removed.

2022-10-13 02:10 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +					THEN '|| Cause,IntervalOrginal,UnitOriginal|Error:DeathCause is null but Death Interval or Death Unit have value' ELSE '' END AS LoadNote_2
Error message changed to 'Cause of death is blank but the interval or unit have value'

2022-10-13 02:13 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		INTO #Tmp_HoldData_Filter
Validation added.

2022-10-13 02:13 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		LEFT JOIN [RVRS_PROD].[RVRS_ODS].[RVRS].[DimDeathCauseUnit] DS WITH(NOLOCK) ON DS.Abbr=MT.UnitOriginal
Fixed

2022-10-13 02:13 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		LEFT JOIN [RVRS_PROD].[RVRS_ODS].[RVRS].[DimDeathCauseUnit] DS WITH(NOLOCK) ON DS.Abbr=MT.Unit1Conv
Fixed

2022-10-13 02:13 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		LEFT JOIN [RVRS_PROD].[RVRS_ODS].[RVRS].[DimDeathCauseUnit] DS WITH(NOLOCK) ON DS.Abbr=MT.Unit1Conv
Fixed

2022-10-13 02:13 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		LEFT JOIN [RVRS_PROD].[RVRS_ODS].[RVRS].[DimDeathCauseUnit] DS WITH(NOLOCK) ON DS.Abbr=MT.Unit2Conv
Fixed

2022-10-13 02:15 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +
Code updated to catch all the records whose dimunitids are NULL.

2022-10-13 20:32 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		INTO #Tmp_HoldData_Filter
As per our discussion we can remove this validation for now.

2022-10-14 21:19 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +	    SELECT TOP 1000 D.DEATH_REC_ID AS SrId
remove top 1000

2022-10-14 21:37 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +				'DimUnitOrginalId|Pending Review:Not a valid DimUnit1ConvId'
Change DimUnitOrginalId to DimUnit1ConvId

2022-10-14 21:37 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		WHERE DimUnit2ConvId IS NULL
change DimUnit1ConvId to DimUnit2ConvId

2022-10-14 21:39 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +
Do you have other conversion

2022-10-14 21:42 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			   ,ISNULL(Cause_DC,Cause)
?

2022-10-14 21:45 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		LEFT JOIN [RVRS].[DeathCauseInterval_Data_Conversion] DC on HD.IntervalOrginal = DC.Interval
load note for Data Conversion

2022-10-14 21:55 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,ISNULL(D.UNITA,'NULL') AS UnitOriginal
It would be safe to convert this to ISNULL to COALESCE

2022-10-14 21:57 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,ISNULL(Unit2Conv,'NULL') AS Unit2Conv
Why do you need these one again?

2022-10-14 22:00 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +	    SELECT TOP 1000 D.DEATH_REC_ID AS SrId
Removed

2022-10-14 22:01 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +				'DimUnitOrginalId|Pending Review:Not a valid DimUnit1ConvId'
Changed to DimUnit1ConvId

2022-10-14 22:01 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		WHERE DimUnit2ConvId IS NULL
Changed to DimUnit2ConvId

2022-10-14 22:03 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +
we have unknowns and value like '-- --', so standardizing those one

2022-10-14 22:04 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			   ,ISNULL(Cause_DC,Cause)
Because we are standardizing some values in Cause for Cause Other.

2022-10-14 22:11 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +		LEFT JOIN [RVRS].[DeathCauseInterval_Data_Conversion] DC on HD.IntervalOrginal = DC.Interval
Do we need Loadnote for this one? We do have original value stored in the fact table too right.

We can discuss this.

2022-10-17 14:04 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,ISNULL(D.UNITA,'NULL') AS UnitOriginal
Fixed

2022-10-17 14:05 UTC, sailendrasingh1 commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +			  ,ISNULL(Unit2Conv,'NULL') AS Unit2Conv
Removed

2022-10-17 14:36 UTC, almabekwoldesenbet commented on RVRS_Staging/Database/Procedure/RVRS.Load_VIP_DeathCausePr.sql
> +	    SELECT TOP 1000 D.DEATH_REC_ID AS SrId
Not resoved

2022-10-17 16:03 UTC, almabekwoldesenbet requested changes
create final version for VET . Test version looks good

2022-10-17 21:20 UTC, almabekwoldesenbet approved these changes
Great work. will be merged

2022-10-17 21:20 UTC, merged